server:
  port: 8080
  servlet:
    context-path: /identify

spring:
  application:
    name: identify-service
  datasource:
    url: jdbc:mysql://localhost:3306/test-sql-java
    username: root
    password: "MX6{[C5Psvn4e3mgweLvwX"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
